#pragma once
#include "glm/vec2.hpp"
#include "Block.hpp"
#include <vector>
#include <string>

namespace Game
{
	class Chunk
	{
	public:
		Chunk(std::shared_ptr<RenderEngine::Texture2D> pTexture,
			  std::shared_ptr<RenderEngine::ShaderProgram> pShaderProgram);

		void render(glm::vec3& camera_position);
		void update(const uint64_t delta);

		void setPosition(glm::vec2 position);
		void setBlocksPositions(std::vector<std::shared_ptr<std::pair<std::string, glm::vec3>>> blocks);
	private:
		glm::vec2 m_position;
		std::unique_ptr<Block> block;
		std::shared_ptr<glm::vec2> m_vec2_blocks_positions[147] = {
												std::make_shared<glm::vec2>(glm::vec2( 0,  0)),
												std::make_shared<glm::vec2>(glm::vec2(-1,  0)),
												std::make_shared<glm::vec2>(glm::vec2(-1, -1)),
												std::make_shared<glm::vec2>(glm::vec2( 0, -1)),
												std::make_shared<glm::vec2>(glm::vec2( 1, -1)),
												std::make_shared<glm::vec2>(glm::vec2( 1,  0)),
												std::make_shared<glm::vec2>(glm::vec2( 1,  1)),
												std::make_shared<glm::vec2>(glm::vec2( 0,  1)),
												std::make_shared<glm::vec2>(glm::vec2(-1,  1)),
												std::make_shared<glm::vec2>(glm::vec2(-2,  1)),
												std::make_shared<glm::vec2>(glm::vec2(-2,  0)),
												std::make_shared<glm::vec2>(glm::vec2(-2, -1)),
												std::make_shared<glm::vec2>(glm::vec2(-2, -2)),
												std::make_shared<glm::vec2>(glm::vec2(-1, -2)),
												std::make_shared<glm::vec2>(glm::vec2( 0, -2)),
												std::make_shared<glm::vec2>(glm::vec2( 1, -2)),
												std::make_shared<glm::vec2>(glm::vec2( 2, -2)),
												std::make_shared<glm::vec2>(glm::vec2( 2, -1)),
												std::make_shared<glm::vec2>(glm::vec2( 2,  0)),
												std::make_shared<glm::vec2>(glm::vec2( 2,  1)),
												std::make_shared<glm::vec2>(glm::vec2( 2,  2)),
												std::make_shared<glm::vec2>(glm::vec2( 1,  2)),
												std::make_shared<glm::vec2>(glm::vec2( 0,  2)),
												std::make_shared<glm::vec2>(glm::vec2(-1,  2)),
												std::make_shared<glm::vec2>(glm::vec2(-2,  2)),
												std::make_shared<glm::vec2>(glm::vec2(-3,  2)),
												std::make_shared<glm::vec2>(glm::vec2(-3,  1)),
												std::make_shared<glm::vec2>(glm::vec2(-3,  0)),
												std::make_shared<glm::vec2>(glm::vec2(-3, -1)),
												std::make_shared<glm::vec2>(glm::vec2(-3, -2)),
												std::make_shared<glm::vec2>(glm::vec2(-3, -3)),
												std::make_shared<glm::vec2>(glm::vec2(-2, -3)),
												std::make_shared<glm::vec2>(glm::vec2(-1, -3)),
												std::make_shared<glm::vec2>(glm::vec2( 0, -3)),
												std::make_shared<glm::vec2>(glm::vec2( 1, -3)),
												std::make_shared<glm::vec2>(glm::vec2( 2, -3)),
												std::make_shared<glm::vec2>(glm::vec2( 3, -3)),
												std::make_shared<glm::vec2>(glm::vec2( 3, -2)),
												std::make_shared<glm::vec2>(glm::vec2( 3, -1)),
												std::make_shared<glm::vec2>(glm::vec2( 3,  0)),
												std::make_shared<glm::vec2>(glm::vec2( 3,  1)),
												std::make_shared<glm::vec2>(glm::vec2( 3,  2)),
												std::make_shared<glm::vec2>(glm::vec2( 3,  3)),
												std::make_shared<glm::vec2>(glm::vec2( 2,  3)),
												std::make_shared<glm::vec2>(glm::vec2( 1,  3)),
												std::make_shared<glm::vec2>(glm::vec2( 0,  3)),
												std::make_shared<glm::vec2>(glm::vec2(-1,  3)),
												std::make_shared<glm::vec2>(glm::vec2(-2,  3)),
												std::make_shared<glm::vec2>(glm::vec2(-3,  3)),
												std::make_shared<glm::vec2>(glm::vec2(-4,  3)),
												std::make_shared<glm::vec2>(glm::vec2(-4,  2)),
												std::make_shared<glm::vec2>(glm::vec2(-4,  1)),
												std::make_shared<glm::vec2>(glm::vec2(-4,  0)),
												std::make_shared<glm::vec2>(glm::vec2(-4, -1)),
												std::make_shared<glm::vec2>(glm::vec2(-4, -2)),
												std::make_shared<glm::vec2>(glm::vec2(-4, -3)),
												std::make_shared<glm::vec2>(glm::vec2(-4, -4)),
												std::make_shared<glm::vec2>(glm::vec2(-3, -4)),
												std::make_shared<glm::vec2>(glm::vec2(-2, -4)),
												std::make_shared<glm::vec2>(glm::vec2(-1, -4)),
												std::make_shared<glm::vec2>(glm::vec2( 0, -4)),
												std::make_shared<glm::vec2>(glm::vec2( 1, -4)),
												std::make_shared<glm::vec2>(glm::vec2( 2, -4)),
												std::make_shared<glm::vec2>(glm::vec2( 3, -4)),
												std::make_shared<glm::vec2>(glm::vec2( 4, -4)),
												std::make_shared<glm::vec2>(glm::vec2( 4, -3)),
												std::make_shared<glm::vec2>(glm::vec2( 4, -2)),
												std::make_shared<glm::vec2>(glm::vec2( 4, -1)),
												std::make_shared<glm::vec2>(glm::vec2( 4,  0)),
												std::make_shared<glm::vec2>(glm::vec2( 4,  1)),
												std::make_shared<glm::vec2>(glm::vec2( 4,  2)),
												std::make_shared<glm::vec2>(glm::vec2( 4,  3)),
												std::make_shared<glm::vec2>(glm::vec2( 4,  4)),
												std::make_shared<glm::vec2>(glm::vec2( 3,  4)),
												std::make_shared<glm::vec2>(glm::vec2( 2,  4)),
												std::make_shared<glm::vec2>(glm::vec2( 1,  4)),
												std::make_shared<glm::vec2>(glm::vec2( 0,  4)),
												std::make_shared<glm::vec2>(glm::vec2(-1,  4)),
												std::make_shared<glm::vec2>(glm::vec2(-2,  4)),
												std::make_shared<glm::vec2>(glm::vec2(-3,  4)),
												std::make_shared<glm::vec2>(glm::vec2(-4,  4)),
												std::make_shared<glm::vec2>(glm::vec2(-5,  4)),
												std::make_shared<glm::vec2>(glm::vec2(-5,  3)),
												std::make_shared<glm::vec2>(glm::vec2(-5,  2)),
												std::make_shared<glm::vec2>(glm::vec2(-5,  1)),
												std::make_shared<glm::vec2>(glm::vec2(-5,  0)),
												std::make_shared<glm::vec2>(glm::vec2(-5, -1)),
												std::make_shared<glm::vec2>(glm::vec2(-5, -2)),
												std::make_shared<glm::vec2>(glm::vec2(-5, -3)),
												std::make_shared<glm::vec2>(glm::vec2(-5, -4)),
												std::make_shared<glm::vec2>(glm::vec2(-5, -5)),
												std::make_shared<glm::vec2>(glm::vec2(-4, -5)),
												std::make_shared<glm::vec2>(glm::vec2(-3, -5)),
												std::make_shared<glm::vec2>(glm::vec2(-2, -5)),
												std::make_shared<glm::vec2>(glm::vec2(-1, -5)),
												std::make_shared<glm::vec2>(glm::vec2( 0, -5)),
												std::make_shared<glm::vec2>(glm::vec2( 1, -5)),
												std::make_shared<glm::vec2>(glm::vec2( 2, -5)),
												std::make_shared<glm::vec2>(glm::vec2( 3, -5)),
												std::make_shared<glm::vec2>(glm::vec2( 4, -5)),
												std::make_shared<glm::vec2>(glm::vec2( 5, -5)),
												std::make_shared<glm::vec2>(glm::vec2( 5, -4)),
												std::make_shared<glm::vec2>(glm::vec2( 5, -3)),
												std::make_shared<glm::vec2>(glm::vec2( 5, -2)),
												std::make_shared<glm::vec2>(glm::vec2( 5, -1)),
												std::make_shared<glm::vec2>(glm::vec2( 5,  0)),
												std::make_shared<glm::vec2>(glm::vec2( 5,  1)),
												std::make_shared<glm::vec2>(glm::vec2( 5,  2)),
												std::make_shared<glm::vec2>(glm::vec2( 5,  3)),
												std::make_shared<glm::vec2>(glm::vec2( 5,  4)),
												std::make_shared<glm::vec2>(glm::vec2( 5,  5)),
												std::make_shared<glm::vec2>(glm::vec2( 4,  5)),
												std::make_shared<glm::vec2>(glm::vec2( 3,  5)),
												std::make_shared<glm::vec2>(glm::vec2( 2,  5)),
												std::make_shared<glm::vec2>(glm::vec2( 1,  5)),
												std::make_shared<glm::vec2>(glm::vec2( 0,  5)),
												std::make_shared<glm::vec2>(glm::vec2(-1,  5)),
												std::make_shared<glm::vec2>(glm::vec2(-2,  5)),
												std::make_shared<glm::vec2>(glm::vec2(-3,  5)),
												std::make_shared<glm::vec2>(glm::vec2(-4,  5)),
												std::make_shared<glm::vec2>(glm::vec2(-5,  5)),
												std::make_shared<glm::vec2>(glm::vec2(-6,  5)),
												std::make_shared<glm::vec2>(glm::vec2(-6,  4)),
												std::make_shared<glm::vec2>(glm::vec2(-6,  3)),
												std::make_shared<glm::vec2>(glm::vec2(-6,  2)),
												std::make_shared<glm::vec2>(glm::vec2(-6,  1)),
												std::make_shared<glm::vec2>(glm::vec2(-6,  0)),
												std::make_shared<glm::vec2>(glm::vec2(-6, -1)),
												std::make_shared<glm::vec2>(glm::vec2(-6, -2)),
												std::make_shared<glm::vec2>(glm::vec2(-6, -3)),
												std::make_shared<glm::vec2>(glm::vec2(-6, -4)),
												std::make_shared<glm::vec2>(glm::vec2(-6, -5)),
												std::make_shared<glm::vec2>(glm::vec2(-6, -6)),
												std::make_shared<glm::vec2>(glm::vec2(-5, -6)),
												std::make_shared<glm::vec2>(glm::vec2(-4, -6)),
												std::make_shared<glm::vec2>(glm::vec2(-3, -6)),
												std::make_shared<glm::vec2>(glm::vec2(-2, -6)),
												std::make_shared<glm::vec2>(glm::vec2(-1, -6)),
												std::make_shared<glm::vec2>(glm::vec2( 0, -6)),
												std::make_shared<glm::vec2>(glm::vec2( 1, -6)),
												std::make_shared<glm::vec2>(glm::vec2( 2, -6)),
												std::make_shared<glm::vec2>(glm::vec2( 3, -6)),
												std::make_shared<glm::vec2>(glm::vec2( 4, -6)),
												std::make_shared<glm::vec2>(glm::vec2( 5, -6)),
												std::make_shared<glm::vec2>(glm::vec2( 6, -6)),
												std::make_shared<glm::vec2>(glm::vec2( 6, -5)),
												std::make_shared<glm::vec2>(glm::vec2( 6, -4))
																};
		std::vector<std::shared_ptr<std::pair<std::string, glm::vec3>>> m_blocks;
	};
}